-- Seed unique courses extracted from the Spring-2025 allocation workbook
INSERT INTO courses (code, title) VALUES
    ('CS-1004', 'Object Oriented Programming (CS)'),
    ('EE-1005', 'Digital Logic Design (CS)'),
    ('CS-1005', 'Discrete Structures (CY)'),
    ('CS-1002', 'Programming Fundamentals (CS)'),
    ('CS-2005', 'Database Systems (CS)'),
    ('CS-2006', 'Operating Systems (CS)'),
    ('AI-2002', 'Artificial Intelligence (AI)'),
    ('EE-2003', 'Computer Organization and Assembly Language (AI)'),
    ('CS-2004', 'Fundamentals of Software Engineering (AI)'),
    ('DS-2003', 'Advanced Statistics (DS)'),
    ('CS-3001', 'Computer Networks (CY)'),
    ('SE-2002', 'Software Design and Architecture (SE)'),
    ('CS-2001', 'Data Structures (CS/CY)'),
    ('CS-3006', 'Parallel and Distributed Computing (CS+Robotics)'),
    ('CS-3009', 'Software Engineering (CS+Robotics)'),
    ('CS-4031', 'Compiler Construction (CS)'),
    ('CS-4032', 'Web Programming (CS-Elective-I)'),
    ('CS-4039', 'Software for Mobile Devices (CS-Elective-I)'),
    ('CS-4085', 'DevOPS (CS Elective-1)'),
    ('CS-4110', 'High Performance Computing with GPUs (CS Elective-1)'),
    ('CS-2008', 'Numerical Computing (BS Robotics)'),
    ('CS-4090', 'Machine Learning for Robotics (BS Robotics)'),
    ('AI-3003', 'Artificial Neural Networks (AI)'),
    ('AI-4001', 'Fundamentals of Natural Language Processing'),
    ('CS-4055', 'Digital Image Processing (AI Elective-I)'),
    ('CS-4082', 'Applied Evolutionary Computing (AI Elective-I)'),
    ('AI-4013', 'AI product Development (AI Elective-I)'),
    ('DS-3002', 'Data Mining (DS)'),
    ('AI-4012', 'Multiagent Systems (DS Elective-1)'),
    ('CS-3002', 'Information Security (CY)'),
    ('CY-3002', 'Vulnearability Assessment and Reverse Engineering (CY)'),
    ('CS-4061', 'Ethical Hacking Concepts and Practices (Cyber Elective II)'),
    ('SE-3001', 'Software Construction & Development (SE)'),
    ('CS-2009', 'Design and Analysis of Algorithms (SE)'),
    ('AI-4007', 'Applied Artificial Intelligence (SE Elective-I)'),
    ('SE-4033', 'Formal Methods in Software Engineering (SE-Supporting-III)'),
    ('CS-3005', 'Theory of Automata'),
    ('SS-2002', 'Software Design and Architecture (SE)'),
    ('CS-4091', 'Final Year Project-I (CS)'),
    ('CS-4092', 'Final Year Project-II (CS)'),
    ('AI-4091', 'Final Year Project-I (AI)'),
    ('AI-4092', 'Final Year Project-II (AI)'),
    ('CS-4001', 'Professional Practices in IT (AI)'),
    ('DS-4091', 'Final Year Project-I (DS)'),
    ('DS-4092', 'Final Year Project-II (DS)'),
    ('CY-4091', 'Final Year Project-I (CY)'),
    ('CY-4092', 'Final Year Project-II (CY)'),
    ('CS-4111', 'Applied Machine Learning for Cyber Security (CY Elective-IV)'),
    ('SE-4091', 'Final Year Project-1 (SE)'),
    ('SE-4092', 'Final Year Project-II (SE)'),
    ('MT-2002', 'Statistical Modelling (CS)'),
    ('AI-4009', 'Generative AI (AI&DS)'),
    ('AI-3004', 'Reinforcement Learning (AI&DS)'),
    ('CS-4063', 'Natural Language Processing (CS)'),
    ('CS-4074', 'User Experience Engineering (CS)'),
    ('CS-4045', 'Deep Learing for Perception (CS)'),
    ('CS-3012', 'Fundamentals of Data Visualization (CS)'),
    ('CS-4059', 'Fundamentals of Computer Vision (CS)'),
    ('CS-4083', 'Distributed Data Engineering (CS)'),
    ('CS-4104', 'Applied Machine Learning (CS)'),
    ('CS-4044', 'Fundamentals of Software Project Management (CS)'),
    ('CS-4075', 'Cloud Computing (CS)'),
    ('CS-4046', 'Game Design and Developement (CS)'),
    ('CS-4049', 'Blockchain and Cryptocurrency (CS)'),
    ('CS-5137', 'Deep Reinforcement Learning'),
    ('CS-5037', 'Data Visualization'),
    ('SE-5004', 'Search-based Software Engineering'),
    ('CS-5130', 'Securing the Internet of Things'),
    ('CS-5057', 'Data Analysis'),
    ('CS-4002', 'Applied Programming'),
    ('CS-5001', 'Research Methodology'),
    ('CS-5006', 'Theory of Programming Languages'),
    ('CS-5091', 'MS Thesis - 1'),
    ('CS-5092', 'MS Thesis - 2'),
    ('CY-5006', 'Advanced Networks Security'),
    ('CN-5091', 'MS Thesis - 1'),
    ('CN-5092', 'MS Thesis - 2'),
    ('SE-5001', 'Advanced Software Requirement Engineering'),
    ('SE-5091', 'MS Thesis - 1'),
    ('SE-5092', 'MS Thesis - 2'),
    ('AI-5003', 'Advanced Machine Learning'),
    ('AI-5091', 'MS Thesis - 1'),
    ('AI-5092', 'MS Thesis - 2'),
    ('DS-5004', 'Machine Learning for Data Science'),
    ('DS-5008', 'Big Data Analytics'),
    ('DS-5006', 'Deep Learning'),
    ('DS-5091', 'MS Thesis - 1'),
    ('DS-5092', 'MS Thesis - 2'),
    ('MG-1001', 'Fundamentals of Management (CS)'),
    ('MG-4033', 'Digital Marketing (DS)'),
    ('MG-1007', 'Freelancing (CS)'),
    ('MG-4049', 'Technopreneurship (CS)'),
    ('MG-4011', 'Entrepreneurship (DS)'),
    ('MT-1008', 'Multivariable Calculus (CS)'),
    ('SS-1014', 'Expository Writing (CS)'),
    ('SS-1013', 'Ideology and Constitution of Pakistan (CS)'),
    ('SS-2019', 'Psychology (SS Elective-1)'),
    ('SS-1019', 'Understanding Seerat un Nabi ﷺ'),
    ('SS-1007', 'Islamic Studies/Ethics (AI)'),
    ('SS-3002', 'Civics and Community Engagement (AI)'),
    ('SS-1018', 'Understanding of Holy Quran (AI)'),
    ('MT-1003', 'Calculus and Analytical Geometry (All Programs)'),
    ('NS-1001', 'Applied Physics'),
    ('MT-2005', 'Probability and Statistics (CS)'),
    ('SS-2012', 'Technical & Business Writing (CS)'),
    ('SS-1008', 'Communication & Presentation Skills'),
    ('SL-1008', 'Communication & Presentation Skills Lab'),
    ('SL-1014', 'Expository Writing Lab (CS)'),
    ('CL-1004', 'Object Oriented Programming Lab (CS)'),
    ('EL-1005', 'Digital Logic Design Lab (CS)'),
    ('CL-1002', 'Programming Fundamentals Lab (CS)'),
    ('CL-2005', 'Database Systems Lab (CS)'),
    ('CL-2006', 'Operating Systems Lab (CS)'),
    ('AL-2002', 'Artificial Intelligence Lab (AI)'),
    ('EL-2003', 'Computer Organization and Assembly Language Lab (AI)'),
    ('CL-3001', 'Computer Networks Lab (CY)'),
    ('CL-2001', 'Data Structures Lab (CS/CY)'),
    ('SL-2002', 'Software Design and Architecture (SE)'),
    ('DL-3002', 'Data Mining Lab (DS)'),
    ('CYL-3002', 'Vulnearability Assessment and Reverse Engineering Lab (CY)'),
    ('SL-3001', 'Software Construction & Development Lab (SE)')
ON CONFLICT (code) DO NOTHING;
