-- Seed faculties based on images in static/images
-- This migration inserts a faculty row for each image file. It uses department lookup from departments table when possible.

INSERT INTO faculties (name, department_id, image_path) VALUES
('Ahmad Raza Shahid', (SELECT id FROM departments WHERE name='CS'), '/images/Ahmad Raza Shahid.webp'),
('Ali Umer', NULL, '/images/Ali Umer.jpg'),
('Arshad Islam', NULL, '/images/Arshad Islam.webp'),
('Dr. Akhtar Jamil', NULL, '/images/Dr. Akhtar Jamil.webp'),
('Dr. Ali Zeeshan Ijaz', (SELECT id FROM departments WHERE name='AI & DS'), '/images/Dr. Ali Zeeshan Ijaz.webp'),
('Dr. Basharat Hussain', NULL, '/images/Dr. Basharat Hussain.webp'),
('Dr. Ejaz Ahmed', NULL, '/images/Dr. Ejaz Ahmed.webp'),
('Dr. Hina Ayaz', (SELECT id FROM departments WHERE name='SE'), '/images/Dr. Hina Ayaz.webp'),
('Dr. Labiba Fahad', NULL, '/images/Dr. Labiba Fahad.webp'),
('Dr. Mehreen Alam', NULL, '/images/Dr. Mehreen Alam.webp'),
('Dr. Muhammad Faisal Cheema', NULL, '/images/Dr. Muhammad Faisal Cheema.webp'),
('Dr. Tajwar Mehmood', NULL, '/images/Dr. Tajwar Mehmood.webp'),
('Furqan Nasir', NULL, '/images/Furqan Nasir.jpg'),
('Hammad Majeed', NULL, '/images/Hammad Majeed.webp'),
('Imran Khan', NULL, '/images/Imran Khan.jpeg'),
('Mr. Aqib Rehman', NULL, '/images/Mr. Aqib Rehman.webp'),
('Mr. Fahad Shafique Mirza', NULL, '/images/Mr. Fahad Shafique Mirza.webp'),
('Mr. Hamza Mahmood Sheikh', NULL, '/images/Mr. Hamza Mahmood Sheikh.webp'),
('Mr. Majid Hussain', NULL, '/images/Mr. Majid Hussain.webp'),
('Mr. Muhammad Aadi Ur Rehman', NULL, '/images/Mr. Muhammad Aadi Ur Rehman.webp'),
('Mr. Muhammad Aamir Gulzar', NULL, '/images/Mr. Muhammad Aamir Gulzar.webp'),
('Mr. Muhammad Almas Khan', NULL, '/images/Mr. Muhammad Almas Khan.webp'),
('Mr. Muhammad Farrukh Bashi', NULL, '/images/Mr. Muhammad Farrukh Bashi.webp'),
('Mr. Muhammad Ismail', NULL, '/images/Mr. Muhammad Ismail.webp'),
('Mr. Muhammad Talha Sharif', NULL, '/images/Mr. Muhammad Talha Sharif.webp'),
('Mr. Owais Idrees', NULL, '/images/Mr. Owais Idrees.webp'),
('Mr. Shams Farooq', NULL, '/images/Mr. Shams Farooq.webp'),
('Mr. Shehreyar Rashid', NULL, '/images/Mr. Shehreyar Rashid.webp'),
('Mr. Syed M.Saad Salman', NULL, '/images/Mr. Syed M.Saad Salman.webp'),
('Mr. Usama Bin Imran', NULL, '/images/Mr. Usama Bin Imran.webp'),
('Ms. Amna Irum', NULL, '/images/Ms. Amna Irum.webp'),
('Ms. Asma Tufail', (SELECT id FROM departments WHERE name='CS'), '/images/Ms. Asma Tufail.webp'),
('Ms. Hajira Uzair', NULL, '/images/Ms. Hajira Uzair.webp'),
('Ms. Hira Mastoo', NULL, '/images/Ms. Hira Mastoo.webp'),
('Ms. Laiba Noor', NULL, '/images/Ms. Laiba Noor.webp'),
('Ms. Marium Hida', NULL, '/images/Ms. Marium Hida.webp'),
('Ms. Maryam Shahbaz', NULL, '/images/Ms. Maryam Shahbaz.webp'),
('Ms. Nirmal Tariq', NULL, '/images/Ms. Nirmal Tariq.webp'),
('Ms. Noor Ul Ain', NULL, '/images/Ms. Noor Ul Ain.webp'),
('Ms. Rabail Zahid', NULL, '/images/Ms. Rabail Zahid.webp'),
('Ms. Zill-E-Huma', NULL, '/images/Ms. Zill-E-Huma.webp'),
('Umair Khalid', NULL, '/images/Umair Khalid.jpeg');

-- Note: Adjust department mapping as needed via update statements after migration.

